# Numpy vs python

In [2]:
l=range(100000)
for i in range(0,10):
    print(l)

range(0, 100000)
range(0, 100000)
range(0, 100000)
range(0, 100000)
range(0, 100000)
range(0, 100000)
range(0, 100000)
range(0, 100000)
range(0, 100000)
range(0, 100000)


In [7]:
%time for i in range(1,10): r=[x*2 for x in l]
  

Wall time: 24 ms


In [8]:
import numpy as np

In [10]:
d=np.arange(100000)

In [11]:
%time for i in range(1,10): r=d*2

Wall time: 12 ms


# ndarray

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        9.34607753e-307],
       [1.89146896e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307],
       [1.78020169e-306, 7.56601165e-307, 1.02359984e-306,
        1.33510679e-306],
       [2.22522597e-306, 1.11260144e-306, 6.89812281e-307,
        2.22522596e-306]])

In [16]:
# converting a list into an array
l=[1,2,3,4,56,7]

In [19]:
x=np.array(l)

In [20]:
np.shape(x)

(6,)

In [29]:
z=np.zeros((10,10))

In [30]:
np.shape(z)

(10, 10)

In [37]:
z.reshape((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [33]:
z.dtype

dtype('float64')

In [34]:
z.ndim

2

# Arthimetic operation with ndarray

In [38]:
#vectorize operation

In [39]:
import numpy as np

In [44]:
a=np.random.randn(4,4)

In [45]:
a

array([[ 0.22757475, -0.79219384, -0.24540072, -0.53217536],
       [-1.31015386, -1.25745728, -1.17296823,  0.93639571],
       [ 1.41215729,  0.11127341,  0.28084129,  0.78021512],
       [-0.59870407, -0.06347851, -1.04636631,  0.89594535]])

In [46]:
b=np.random.randn(4,4)

In [47]:
a+b

array([[ 1.42045809, -1.56009428,  0.154342  , -0.95380183],
       [-1.90530091, -1.9555307 , -1.36204389,  0.99609512],
       [ 2.53420855, -0.32227003,  3.11483086,  0.45371365],
       [-2.05664708, -0.48795356, -1.53146348,  2.04996429]])

In [48]:
a-b

array([[-0.9653086 , -0.02429339, -0.64514344, -0.11054889],
       [-0.71500682, -0.55938385, -0.98389256,  0.87669629],
       [ 0.29010602,  0.54481686, -2.55314828,  1.10671659],
       [ 0.85923894,  0.36099655, -0.56126915, -0.2580736 ]])

In [49]:
a*b

array([[ 0.27147012,  0.608326  , -0.09809715,  0.22437922],
       [ 0.7797342 ,  0.87779751,  0.22177975,  0.05590228],
       [ 1.58451287, -0.04824186,  0.79590129, -0.25474138],
       [ 0.87287641,  0.02694504,  0.50758933,  1.0339379 ]])

In [50]:
a/b

array([[ 0.19077703,  1.03163612, -0.61389665,  1.26219628],
       [ 2.20139522,  1.80132523,  6.20369749, 15.68517359],
       [ 1.2585497 , -0.25666035,  0.0990975 , -2.38962207],
       [ 0.41064985,  0.14954591,  2.1570242 ,  0.7763697 ]])

In [51]:
1/a

array([[  4.39416069,  -1.26231732,  -4.07496771,  -1.87907985],
       [ -0.76326913,  -0.79525565,  -0.85253801,   1.06792459],
       [  0.70813642,   8.98687272,   3.56072995,   1.2816978 ],
       [ -1.67027426, -15.75336383,  -0.95568826,   1.11613951]])

In [52]:
a**2

array([[0.05179026, 0.62757107, 0.06022151, 0.28321062],
       [1.71650314, 1.5811988 , 1.37585447, 0.87683692],
       [1.99418821, 0.01238177, 0.07887183, 0.60873563],
       [0.35844656, 0.00402952, 1.09488246, 0.80271806]])

In [53]:
a>0

array([[ True, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [False, False, False,  True]])

In [54]:
a[a>0]

array([0.22757475, 0.93639571, 1.41215729, 0.11127341, 0.28084129,
       0.78021512, 0.89594535])

# indexing and slicing

In [58]:
sl=np.ones((10,10))

In [59]:
sl

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [63]:
sl[1:-1,1:-1]=0

In [64]:
sl

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
sl[1][-1]

1.0

In [75]:
sl[::,0:4]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
sl

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [78]:
sl[0:4,::]=1

In [79]:
sl

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# fast element wise array function

In [81]:
import numpy as np


In [83]:
a=np.array([10,73,8,-1,3,1])

In [84]:
a


array([10, 73,  8, -1,  3,  1])

In [85]:
b=np.array([1,88,99,5,-10,23])

In [86]:
b

array([  1,  88,  99,   5, -10,  23])

In [87]:
np.sqrt(a)

C:\Users\Aqeel\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([3.16227766, 8.54400375, 2.82842712,        nan, 1.73205081,
       1.        ])

In [88]:
np.power(a,2)

array([ 100, 5329,   64,    1,    9,    1], dtype=int32)

In [89]:
np.maximum(a,b)

array([10, 88, 99,  5,  3, 23])

# Where in Numpy

In [90]:
import numpy as np


In [91]:
salary=np.array([-1,0,99999,80000])

In [92]:
np.where(salary<=0,25000,salary)

array([25000, 25000, 99999, 80000])

In [93]:
np.where(salary<=0,"NOt Ok", "Ok")

array(['NOt Ok', 'NOt Ok', 'Ok', 'Ok'], dtype='<U6')

# Mathematical and statistical methods/ Function

In [94]:
x=np.array([10,9,1,222,3])

In [95]:
x

array([ 10,   9,   1, 222,   3])

In [96]:
np.cumsum(x)

array([ 10,  19,  20, 242, 245], dtype=int32)

In [97]:
np.cumproduct(x)

array([   10,    90,    90, 19980, 59940], dtype=int32)

In [98]:
np.cumprod(x)

array([   10,    90,    90, 19980, 59940], dtype=int32)

In [99]:
np.sum(x)

245

In [105]:
y=x>9
y

array([ True, False, False,  True, False])

In [101]:
y.sum()

2

In [106]:
y.any()

True

In [107]:
y.all()

False

In [108]:
x.sort()

In [109]:
x

array([  1,   3,   9,  10, 222])

In [111]:
np.unique(x)

array([  1,   3,   9,  10, 222])

# File Input Output

In [127]:
a=[1,2,3,4,5,6]

In [128]:
b=[2,3,45,7,8,9]

In [129]:
np.save("test",a)

In [130]:
loada=np.load("test.npy")

In [131]:
loada

array([1, 2, 3, 4, 5, 6])

In [151]:
np.savez('test.npz',a,b)

In [152]:
loadab=np.load('test.npz')

In [153]:
loadab

In [155]:
loadab[a,b]

TypeError: not all arguments converted during string formatting

# linear algebra function

In [156]:
x=np.random.randn(2,3)

In [157]:
y=np.random.randn(3,2)

In [158]:
y

array([[-1.53138413, -2.14688898],
       [ 0.77692729,  1.22353707],
       [ 0.46502482,  0.49708159]])

In [159]:
x.dot(y)

array([[-3.19351595, -4.44326052],
       [ 0.43797284,  0.2627221 ]])

In [160]:
x.transpose()

array([[ 2.02076135, -0.07575451],
       [ 0.00220146, -0.6209684 ],
       [-0.21647115,  1.72982352]])

In [161]:
x.trace()

1.3997929498417037

In [162]:
x

array([[ 2.02076135,  0.00220146, -0.21647115],
       [-0.07575451, -0.6209684 ,  1.72982352]])

# PSEUDO RANDOM NUMBER

In [172]:
r=np.random.seed(2)
r

In [174]:
np.random.normal(size=(3,3))

array([[-0.05626683, -2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737,  0.50288142],
       [-1.24528809, -1.05795222, -0.90900761]])

In [176]:
np.random.uniform(size=(3,3))

array([[0.62113383, 0.52914209, 0.13457995],
       [0.51357812, 0.18443987, 0.78533515],
       [0.85397529, 0.49423684, 0.84656149]])

# Reshape in NUmpy

In [178]:
x=np.random.randn(4,5)

In [179]:
x

array([[ 0.80630807, -1.90200089, -1.68871762, -1.93437335,  0.19514905],
       [ 1.51584091,  0.05893885,  0.6049346 , -0.22022558, -0.6885758 ],
       [-0.29189217,  1.09267069,  1.40473201,  0.53980165, -0.52828235],
       [-0.84426073, -2.19216319,  0.36797387,  0.19915186, -2.91949847]])

In [180]:
#use to convert array in one dimensional
x.ravel()

array([ 0.80630807, -1.90200089, -1.68871762, -1.93437335,  0.19514905,
        1.51584091,  0.05893885,  0.6049346 , -0.22022558, -0.6885758 ,
       -0.29189217,  1.09267069,  1.40473201,  0.53980165, -0.52828235,
       -0.84426073, -2.19216319,  0.36797387,  0.19915186, -2.91949847])

In [182]:
#use to convert array in one dimensional
x.flatten()

array([ 0.80630807, -1.90200089, -1.68871762, -1.93437335,  0.19514905,
        1.51584091,  0.05893885,  0.6049346 , -0.22022558, -0.6885758 ,
       -0.29189217,  1.09267069,  1.40473201,  0.53980165, -0.52828235,
       -0.84426073, -2.19216319,  0.36797387,  0.19915186, -2.91949847])

In [186]:
x.reshape(2,2,5)

array([[[ 0.80630807, -1.90200089, -1.68871762, -1.93437335,
          0.19514905],
        [ 1.51584091,  0.05893885,  0.6049346 , -0.22022558,
         -0.6885758 ]],

       [[-0.29189217,  1.09267069,  1.40473201,  0.53980165,
         -0.52828235],
        [-0.84426073, -2.19216319,  0.36797387,  0.19915186,
         -2.91949847]]])

In [187]:
x.reshape(2,2,-1)

array([[[ 0.80630807, -1.90200089, -1.68871762, -1.93437335,
          0.19514905],
        [ 1.51584091,  0.05893885,  0.6049346 , -0.22022558,
         -0.6885758 ]],

       [[-0.29189217,  1.09267069,  1.40473201,  0.53980165,
         -0.52828235],
        [-0.84426073, -2.19216319,  0.36797387,  0.19915186,
         -2.91949847]]])

In [188]:
y=np.random.randn(5,4)

In [189]:
y

array([[-1.15925113, -0.85142751,  1.12721446, -0.38401466],
       [-0.72255835,  1.41621298,  0.57014127, -1.59014501],
       [-0.06352438, -2.4417338 , -1.79591943, -1.02477173],
       [ 0.44430432,  0.04789425, -0.33765127, -0.70014765],
       [-1.14533806,  0.63219177,  1.81669697, -1.05138862]])

In [193]:
y.reshape(5,2,2)

array([[[-1.15925113, -0.85142751],
        [ 1.12721446, -0.38401466]],

       [[-0.72255835,  1.41621298],
        [ 0.57014127, -1.59014501]],

       [[-0.06352438, -2.4417338 ],
        [-1.79591943, -1.02477173]],

       [[ 0.44430432,  0.04789425],
        [-0.33765127, -0.70014765]],

       [[-1.14533806,  0.63219177],
        [ 1.81669697, -1.05138862]]])

# concatenation

In [195]:
a=[[1,2,3,4,5],[5,4,3,2,1]]
b=[[11,22,33,44,55],[55,44,33,22,11]]

In [196]:
arr1=np.array(a)

In [197]:
arr2=np.array(b)

In [232]:
print(np.dstack((arr1,arr2)))

[[[ 1 11]
  [ 2 22]
  [ 3 33]
  [ 4 44]
  [ 5 55]]

 [[ 5 55]
  [ 4 44]
  [ 3 33]
  [ 2 22]
  [ 1 11]]]


In [201]:
np.concatenate((arr1,arr2),axis=0) # row wise concatenation

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [11, 22, 33, 44, 55],
       [55, 44, 33, 22, 11]])

In [203]:
np.concatenate((arr1,arr2),axis=1) # column wise concatenation

array([[ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55],
       [ 5,  4,  3,  2,  1, 55, 44, 33, 22, 11]])

In [204]:
np.vstack((arr1,arr2)) # row wise concatenation

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [11, 22, 33, 44, 55],
       [55, 44, 33, 22, 11]])

In [207]:
np.hstack((arr1,arr2)) # column wise concatenation

array([[ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55],
       [ 5,  4,  3,  2,  1, 55, 44, 33, 22, 11]])

# Split

In [213]:
x=[[1,2,3,4,5,6],[7,8,9,10,11,12]]

In [216]:
np.split(x,[2,4],axis=1)

[array([[1, 2],
        [7, 8]]), array([[ 3,  4],
        [ 9, 10]]), array([], shape=(2, 0), dtype=int32)]

# Repeat and Tile

In [217]:
y=[1,23,45,63]

In [218]:
np.repeat(y,3)

array([ 1,  1,  1, 23, 23, 23, 45, 45, 45, 63, 63, 63])

In [223]:
np.tile(y,3)

TypeError: tile() got an unexpected keyword argument 'axis'

In [224]:
y

[1, 23, 45, 63]

In [228]:
a=np.array([67.98,-10,25,-22.06,0.,12.90,10.10])
print(a.astype(np.int32))

[ 67 -10  25 -22   0  12  10]


In [229]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr%2==1]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [234]:
arr=np.arange(10)
arr_slice=arr[8:5]
arr_slice[:]=69
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [235]:
print(np.arange(9,-1,-1))

[9 8 7 6 5 4 3 2 1 0]


In [237]:
a=np.array([0,1])
b=np.array([0,2])
print(np.column_stack((a,b)))

[[0 0]
 [1 2]]


In [241]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
print(np.concatenate([a,b],axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [242]:
print(np.vstack([a,b]))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [243]:
print(np.r_[a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [244]:
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(np.hsplit(a,3))

[array([[10],
       [40],
       [70]]), array([[20],
       [50],
       [80]]), array([[30],
       [60],
       [90]])]


In [246]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr=np.arange(10)
print(arr.reshape(2,-1))

[[0 1 2 3 4]
 [5 6 7 8 9]]
