In [8]:
import pandas as pd
import numpy as np


In [9]:
a=[1,2,3]
b=[2,3,4]
c=a.append(b)
c

In [10]:
pd.Series([])

Series([], dtype: float64)

In [12]:
frame=pd.DataFrame({'a':[0,1,0,1],'b':[4,7,-3,2]})
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [13]:
arr=np.arange(12).reshape((3,4))
print(arr-arr[0])

[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]
